wallpaper {
  monitor=HDMI-A-2
  path=/home/sl4y/.config/hypr/wallpaper.png
}

wallpaper {
  monitor=DP-1
  path=/home/sl4y/.config/hypr/wallpaper.png
}

wallpaper {
  monitor=HDMI-A-1
  path=/home/sl4y/.config/hypr/wallpaper.png
}

splash=false
