general {
    lock_cmd = pidof hyprlock || hyprlock       # Ekranı kilitleme komutu
    before_sleep_cmd = loginctl lock-session    # Uyku öncesi kilitle
    after_sleep_cmd = hyprctl dispatch dpms on  # Uyandıktan sonra ekranı aç
}

listener {
    timeout = 300                                # 5 dakika
    on-timeout = loginctl lock-session           # Süre dolunca kilitle
}

listener {
    timeout = 330                                # 5.5 dakika
    on-timeout = hyprctl dispatch dpms off       # Ekranı kapat (enerji tasarrufu)
    on-resume = hyprctl dispatch dpms on         # Hareket algılayınca ekranı aç
}
